sonar.projectKey=pubsub-kafka-migrator
sonar.projectName=PubSub to Kafka Migrator
sonar.projectVersion=0.1.0

sonar.sources=platform-common/src/main,platform-project/src/main,platform-job/src/main,platform-orchestrator/src/main
sonar.tests=platform-common/src/test,platform-project/src/test,platform-job/src/test,platform-orchestrator/src/test

sonar.java.binaries=platform-common/build/classes/java/main,platform-project/build/classes/java/main,platform-job/build/classes/java/main,platform-orchestrator/build/classes/java/main

sonar.java.source=21
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/build/**,**/.gradle/**,**/infra/postgres/**
